# Mock in-memory "database" for the demo.
# Replace with real DB / POS integration (e.g. Postgres, Toast, Square, OpenTable) in production.

MENU = [
    {"name": "Margherita Pizza", "category": "Main", "price": 12.99,
     "vegan": False, "vegetarian": True, "gluten_free": False, "allergens": ["dairy", "gluten"]},
    {"name": "Vegan Buddha Bowl", "category": "Main", "price": 11.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Grilled Salmon", "category": "Main", "price": 18.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Caesar Salad", "category": "Starter", "price": 8.50,
     "vegan": False, "vegetarian": False, "gluten_free": False, "allergens": ["dairy", "gluten", "egg"]},
    {"name": "Chocolate Lava Cake", "category": "Dessert", "price": 7.00,
     "vegan": False, "vegetarian": True, "gluten_free": False, "allergens": ["dairy", "gluten", "egg"]},

    # ---- Nigerian local cuisine ----
    {"name": "Jollof Rice", "category": "Main", "price": 9.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": []},
    {"name": "Egusi Soup", "category": "Soup", "price": 10.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Ogbono Soup", "category": "Soup", "price": 10.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Oha Soup", "category": "Soup", "price": 11.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Owerri Soup", "category": "Soup", "price": 12.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish", "crustacean"]},
    {"name": "White Soup (Ofe Nsala)", "category": "Soup", "price": 11.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Bitter Leaf Soup (Ofe Onugbu)", "category": "Soup", "price": 11.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Pounded Yam", "category": "Swallow", "price": 4.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Fufu", "category": "Swallow", "price": 3.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Amala", "category": "Swallow", "price": 3.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Suya", "category": "Grill", "price": 8.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["peanut"]},
    {"name": "Pepper Soup", "category": "Soup", "price": 9.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": []},
    {"name": "Efo Riro", "category": "Soup", "price": 10.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Moin Moin", "category": "Breakfast", "price": 4.50,
     "vegan": False, "vegetarian": True, "gluten_free": True, "allergens": ["egg"]},
    {"name": "Akara", "category": "Breakfast", "price": 3.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Ofada Rice with Ayamase", "category": "Main", "price": 11.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": []},
    {"name": "Nkwobi", "category": "Delicacy", "price": 9.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": []},
    {"name": "Asun", "category": "Grill", "price": 9.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": []},
    {"name": "Nigerian Fried Rice", "category": "Main", "price": 9.50,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["shellfish"]},
    {"name": "Banga Soup", "category": "Soup", "price": 11.00,
     "vegan": False, "vegetarian": False, "gluten_free": True, "allergens": ["fish"]},
    {"name": "Chin Chin", "category": "Dessert", "price": 3.00,
     "vegan": False, "vegetarian": True, "gluten_free": False, "allergens": ["gluten", "egg", "dairy"]},
    {"name": "Puff Puff", "category": "Dessert", "price": 3.00,
     "vegan": True, "vegetarian": True, "gluten_free": False, "allergens": ["gluten"]},

    {"name": "Puff Puff & Pap (Akamu)", "category": "Breakfast", "price": 5.00,
     "vegan": False, "vegetarian": True, "gluten_free": False, "allergens": ["gluten"]},
    {"name": "Agege Bread & Beef Stew", "category": "Breakfast", "price": 7.50,
     "vegan": False, "vegetarian": False, "gluten_free": False, "allergens": ["gluten"]},
    {"name": "Continental Breakfast Platter", "category": "Breakfast", "price": 9.00,
     "vegan": False, "vegetarian": True, "gluten_free": False, "allergens": ["gluten", "dairy", "egg"]},

    # ---- Wine ----
    {"name": "Four Cousins", "category": "Wine", "price": 15.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Carlo Rossi", "category": "Wine", "price": 14.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "4th Street", "category": "Wine", "price": 15.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Apothic Red", "category": "Wine", "price": 17.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Drostdy Hof", "category": "Wine", "price": 14.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Baron Romero", "category": "Wine", "price": 13.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Dominio Del Rey", "category": "Wine", "price": 16.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Eva Wine", "category": "Wine", "price": 10.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Veleta", "category": "Wine", "price": 10.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},
    {"name": "Pure Heaven", "category": "Wine", "price": 10.50,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": ["sulfites"]},

    # ---- Soft drinks ----
    {"name": "Coca-Cola", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Fanta", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Sprite", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Pepsi", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Mirinda", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "7Up", "category": "Soft Drink", "price": 2.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Bigi", "category": "Soft Drink", "price": 1.80,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Teem", "category": "Soft Drink", "price": 1.80,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Schweppes", "category": "Soft Drink", "price": 2.20,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Malta Guinness", "category": "Soft Drink", "price": 2.50,
     "vegan": True, "vegetarian": True, "gluten_free": False, "allergens": ["gluten"]},
    {"name": "Maltina", "category": "Soft Drink", "price": 2.50,
     "vegan": True, "vegetarian": True, "gluten_free": False, "allergens": ["gluten"]},

    # ---- Bottled water ----
    {"name": "Eva Water", "category": "Water", "price": 1.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Ragolis", "category": "Water", "price": 1.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Nestle Pure Life", "category": "Water", "price": 1.20,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "SWAN Table Water", "category": "Water", "price": 1.20,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "CWAY Table Water", "category": "Water", "price": 0.90,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Aquafina", "category": "Water", "price": 1.20,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Aquapac", "category": "Water", "price": 1.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
    {"name": "Aquadana", "category": "Water", "price": 1.00,
     "vegan": True, "vegetarian": True, "gluten_free": True, "allergens": []},
]

# Maps each menu category to a representative photo shown in the app's menu gallery.
# Add more as you upload photos for other categories (Soup, Dessert, Grill, Wine, etc.)
CATEGORY_IMAGES = {
    "Water": "assets/categories/water.png",
    "Wine": "assets/categories/wine.png",
    "Soup": "assets/categories/soup.png",
    "Main": "assets/categories/main.png",
    "Starter": "assets/categories/starter.png",
    "Swallow": "assets/categories/swallow.png",
    "Grill": "assets/categories/grill.png",
    "Delicacy": "assets/categories/delicacy.png",
    "Soft Drink": "assets/categories/soft_drink.png",
    "Dessert": "assets/categories/dessert.png",
    "Breakfast": "assets/categories/breakfast.png",
}

RESTAURANT_HOURS = {
    "Monday": "11:00 AM - 10:00 PM",
    "Tuesday": "11:00 AM - 10:00 PM",
    "Wednesday": "11:00 AM - 10:00 PM",
    "Thursday": "11:00 AM - 10:00 PM",
    "Friday": "11:00 AM - 11:00 PM",
    "Saturday": "10:00 AM - 11:00 PM",
    "Sunday": "10:00 AM - 9:00 PM",
}

DAILY_SPECIALS = [
    {"name": "Truffle Risotto", "price": 16.00, "description": "Creamy risotto with black truffle shavings"},
    {"name": "Iced Passionfruit Tea", "price": 4.50, "description": "House-made, 20% off today"},
]
